name = "visit-stats-worker"
main = "worker.js"
compatibility_date = "2024-09-19"

[durable_objects]
bindings = [
  { name = "COUNTER_DO", class_name = "CounterDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["CounterDO"]

